### ISSUE TITLE
max_in limit dictionary?

### ISSUE THREAD

**Issue by lixingyi8947** [HuguesTHOMAS/KPConv-PyTorch#16]
I encounter the error below when I run train_SemanticKitti.py. I did not find the file named "max_in_limits.pkl". Could you give any hints? Thanks!

Starting Calibration of max_in_points value (use verbose=True for more details)

Previous calibration found:
Check max_in limit dictionary
"balanced_4.000_0.060": ?
Traceback (most recent call last):

  File "<ipython-input-8-e7c16434e2ea>", line 1, in <module>
    training_sampler.calib_max_in(config, training_loader, verbose=True)

  File "/media/xingyi/Tools4TB/KPConv-PyTorch/datasets/SemanticKitti.py", line 905, in calib_max_in
    for batch_i, batch in enumerate(dataloader):

  File "/home/xingyi/miniconda3/envs/torch1.4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)

  File "/home/xingyi/miniconda3/envs/torch1.4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 746, in __init__
    self._try_put_index()

  File "/home/xingyi/miniconda3/envs/torch1.4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 861, in _try_put_index
    index = self._next_index()

  File "/home/xingyi/miniconda3/envs/torch1.4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 339, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration

  File "/home/xingyi/miniconda3/envs/torch1.4/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 200, in __iter__
    for idx in self.sampler:

  File "/media/xingyi/Tools4TB/KPConv-PyTorch/datasets/SemanticKitti.py", line 797, in __iter__
    self.dataset.epoch_inds += gen_indices

RuntimeError: The size of tensor a (4400) must match the size of tensor b (4084) at non-singleton dimension 0

**Comment by HuguesTHOMAS** [comment]
The code will create the file `max_in_limits.pkl`. 

Do you have the latest version of the code? I think I corrected a bug like this one a while ago.

**Comment by lixingyi8947** [comment]
@HuguesTHOMAS Hi, I re downloaded the code and the issue still there. I noticed the most recent change on this repo is two month ago. Am I on the right repo https://github.com/HuguesTHOMAS/KPConv-PyTorch?

**Comment by HuguesTHOMAS** [comment]
Yes you are. Ok I'll look into that as soon as I can this week

**Comment by lixingyi8947** [comment]
@HuguesTHOMAS Thank you very much for your help!

**Comment by HuguesTHOMAS** [comment]
I pushed a correction. I should work now, but tell me if you encounter another bug

**Comment by lixingyi8947** [comment]
@HuguesTHOMAS Hi, I still get the error bellow. It looks the issue still there.


  File "<ipython-input-7-d81a65316711>", line 1, in <module>
    training_sampler.calib_max_in(config, training_loader, verbose=True)

  File "/media/xingyi/Tools4TB/KPConv-PyTorch/datasets/SemanticKitti.py", line 905, in calib_max_in
    for batch_i, batch in enumerate(dataloader):

  File "/home/xingyi/miniconda3/envs/torch1.4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)

  File "/home/xingyi/miniconda3/envs/torch1.4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 746, in __init__
    self._try_put_index()

  File "/home/xingyi/miniconda3/envs/torch1.4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 861, in _try_put_index
    index = self._next_index()

  File "/home/xingyi/miniconda3/envs/torch1.4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 339, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration

  File "/home/xingyi/miniconda3/envs/torch1.4/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 200, in __iter__
    for idx in self.sampler:

  File "/media/xingyi/Tools4TB/KPConv-PyTorch/datasets/SemanticKitti.py", line 797, in __iter__
    self.dataset.epoch_inds += gen_indices

RuntimeError: The size of tensor a (4400) must match the size of tensor b (4084) at non-singleton dimension 0

**Comment by lixingyi8947** [comment]
@HuguesTHOMAS Thanks for your debugging! I made some small changes to my it runnable on my environment (PyTorch 1.4). The details are as below. Please check if you want to merge the changes.

For SemanticKitti.py Line 768:

if class_n < class_potentials.shape[0]:
    _, class_indices = torch.topk(class_potentials, class_n, largest=False)
else:
    class_indices = torch.zeros((0,), dtype=torch.int32)
    while class_indices.shape[0] < class_n:
        new_class_inds = torch.randperm(class_potentials.shape[0]).int()
        class_indices = torch.cat((class_indices, new_class_inds), dim=0)
    class_indices = class_indices[:class_n]
class_indices = self.dataset.class_frames[i][class_indices.long()]
